### ISSUE TITLE
database: category information stored for "kids"

### ISSUE THREAD

**Issue by lindsgray** [shaala/HelpingHandsAPI#4]
• Clothes

1. 
2. Shirts
3. Pants
4. Coats
5. Underwear/Socks
6. Shoes
7. Dresses
8. Skirts
9. Suits

• Personal Care

1. Soap
2. Lotion
3. Shampoo
4. Conditioner
5. Deodorant
6. Toothpaste
7. Toothbrushes
8. Mouthwash
9. Sunscreen

• Baby Care

1. Diapers
2. Baby wipes
3. Formula
4. Bottles
5. Pacifiers
6. Baby clothes
7. Baby blankets

**Comment by ChristaFox** [comment]
These are separated into 4 tables. I can link baby to kids in routes in the api.
